### PR TITLE
WM4-Vanipriya_Piramanathan-Full-Stack-Project-Assessment

### PR DESCRIPTION
**Pull request by Vanipriyaarun**

### CODE REVIEW

**Comment by Dedekind561** [comment]
Hi there @Vanipriyaarun,
When I run `npm start` I can get an error on my local machine. We can't review your PR properly until your code runs. Please let me know when you've fixed this issue.

**Review by Dedekind561 — CHANGES_REQUESTED** [review]
Hey there @Vanipriyaarun, 
Thank you for your submission.
Your code doesn't run on my local machine at the moment - I'm getting an error when I run `npm start`. Please can you fix this problem so we can start reviewing your work.

**Comment by Vanipriyaarun** [comment]
It is running on my machine without any error. The front end is in client folder. Please check again and let me know if error persits. Thanks.

**Comment by Vanipriyaarun** [comment]
I am wondering if you had checked my code again. It works in my system, Please let me know if the error occurs again.

**Pull request closed without merging**
