### PR TITLE
Tresor-Bipa- Full-Stack-Project-Assessment

### PR DESCRIPTION
**Pull request by TresorBipa**

### CODE REVIEW

**Comment by SallyMcGrath** [comment]
Hi there @TresorBipa . Thanks for this. Please update your PR title with your region so mentors know who is who. Thanks! 😄

**Comment by SallyMcGrath** [comment]
@TresorBipa you can just update the name - no need to close the whole thing!

**Comment by TresorBipa** [comment]
Oh sorry Sally for deleting the whole repo

**Comment by TresorBipa** [comment]
I will pull request it just in second again
 Thanks

**Comment by TresorBipa** [comment]
Hi There @SallyMcGrath , I was struggling to pull request my work since then after making a mistake on deleting the whole repo, What should i do now.  Because i am not able to reopen or pull request again.

**Comment by SallyMcGrath** [comment]
Hi @TresorBipa don't worry your work is still here.

If you want to checkout this pr you can do it in the terminal with `gh pr checkout 182`

**Pull request closed without merging**
