### PR TITLE
WM4 - Irina Mihai - Full-Stack-Project-Assessment

### PR DESCRIPTION
**Pull request by irinamihai150**

### CODE REVIEW

**Review by SallyMcGrath — CHANGES_REQUESTED** [review]
Hi @irinamihai150 . There are 171 files in this PR. Which ones were you hoping mentors review? 😉

Would it be a good idea to open a PR only with the pertinent files? (Never git add . in a codebase)

**Comment by irinamihai150** [comment]
I am not sure on how to fix this issue now

**Comment by irinamihai150** [comment]
I tryed to fix but  made it worst. Should I create a new project?

**Comment by SallyMcGrath** [comment]
https://www.google.com/search?q=how+to+remove+node+modules+from+git

There are lots of people in the same position on this PR list!.I suggest you all work together with a mentor in your class channel to clean up your branches. 🧹 

When you work in a team in Final Projects, being organised and intentional about what files you commit and how you describe your changes will make an enormous difference to your team's ability to progress. Work on this with your cohort this week! It's a good opportunity to get to grips with these ideas. You will need them a lot in your job.

(Also, please open a PR per week not one with many levels in -- again, this is all about communicating clearly in code.) 

Good luck!

**Pull request closed without merging**
